package com.polstat.uasppk

import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import retrofit2.Call
import retrofit2.Callback
import retrofit2.Response

class CreateSurveyActivity : AppCompatActivity() {
    private lateinit var titleEditText: EditText
    private lateinit var descriptionEditText: EditText
    private lateinit var createSurveyButton: Button
    private lateinit var apiService: ApiService

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_create_survey)

        titleEditText = findViewById(R.id.titleEditText)
        descriptionEditText = findViewById(R.id.descriptionEditText)
        createSurveyButton = findViewById(R.id.createSurveyButton)
        apiService = ApiClient.instance

        createSurveyButton.setOnClickListener {
            createSurvey()
        }
    }

    private fun createSurvey() {
        val title = titleEditText.text.toString().trim()
        val description = descriptionEditText.text.toString().trim()

        if (title.isEmpty() || description.isEmpty()) {
            Toast.makeText(this, "Please fill in all fields", Toast.LENGTH_SHORT).show()
            return
        }

        val newSurvey = Survey(0, title, description) // ID will be auto-generated by the backend
        apiService.createSurvey(newSurvey).enqueue(object : Callback<Survey> {
            override fun onResponse(call: Call<Survey>, response: Response<Survey>) {
                if (response.isSuccessful) {
                    Toast.makeText(this@CreateSurveyActivity, "Survey Created!", Toast.LENGTH_SHORT).show()
                    finish()
                } else {
                    Toast.makeText(this@CreateSurveyActivity, "Failed to create survey", Toast.LENGTH_SHORT).show()
                }
            }

            override fun onFailure(call: Call<Survey>, t: Throwable) {
                Toast.makeText(this@CreateSurveyActivity, "Network error, try again!", Toast.LENGTH_SHORT).show()
            }
        })
    }
}
